#!/bin/bash
# add_all_urls.sh - Script to add all URLs to urls.txt

cat > urls.txt << 'EOD'
https://www.encodeproject.org/files/ENCFF311CFI/@@download/ENCFF311CFI.tsv
https://www.encodeproject.org/files/ENCFF807IMZ/@@download/ENCFF807IMZ.tsv
https://www.encodeproject.org/files/ENCFF289GIJ/@@download/ENCFF289GIJ.tsv
https://www.encodeproject.org/files/ENCFF248IRI/@@download/ENCFF248IRI.tsv
https://www.encodeproject.org/files/ENCFF438VWX/@@download/ENCFF438VWX.tsv
https://www.encodeproject.org/files/ENCFF608YRR/@@download/ENCFF608YRR.tsv
https://www.encodeproject.org/files/ENCFF275KID/@@download/ENCFF275KID.tsv
https://www.encodeproject.org/files/ENCFF284WWS/@@download/ENCFF284WWS.tsv
https://www.encodeproject.org/files/ENCFF643LAA/@@download/ENCFF643LAA.tsv
https://www.encodeproject.org/files/ENCFF223GDG/@@download/ENCFF223GDG.tsv
https://www.encodeproject.org/files/ENCFF948LZZ/@@download/ENCFF948LZZ.tsv
https://www.encodeproject.org/files/ENCFF555DJM/@@download/ENCFF555DJM.tsv
https://www.encodeproject.org/files/ENCFF882TPE/@@download/ENCFF882TPE.tsv
https://www.encodeproject.org/files/ENCFF866WKT/@@download/ENCFF866WKT.tsv
https://www.encodeproject.org/files/ENCFF525JTH/@@download/ENCFF525JTH.tsv
https://www.encodeproject.org/files/ENCFF599TLF/@@download/ENCFF599TLF.tsv
https://www.encodeproject.org/files/ENCFF628ECY/@@download/ENCFF628ECY.tsv
https://www.encodeproject.org/files/ENCFF437SJZ/@@download/ENCFF437SJZ.tsv
https://www.encodeproject.org/files/ENCFF780DNA/@@download/ENCFF780DNA.tsv
https://www.encodeproject.org/files/ENCFF253ZGO/@@download/ENCFF253ZGO.tsv
https://www.encodeproject.org/files/ENCFF242MYG/@@download/ENCFF242MYG.tsv
https://www.encodeproject.org/files/ENCFF526HYL/@@download/ENCFF526HYL.tsv
https://www.encodeproject.org/files/ENCFF611UYV/@@download/ENCFF611UYV.tsv
https://www.encodeproject.org/files/ENCFF886ERU/@@download/ENCFF886ERU.tsv
https://www.encodeproject.org/files/ENCFF989HJA/@@download/ENCFF989HJA.tsv
https://www.encodeproject.org/files/ENCFF961RUA/@@download/ENCFF961RUA.tsv
https://www.encodeproject.org/files/ENCFF341CEM/@@download/ENCFF341CEM.tsv
https://www.encodeproject.org/files/ENCFF797YXW/@@download/ENCFF797YXW.tsv
https://www.encodeproject.org/files/ENCFF675WZL/@@download/ENCFF675WZL.tsv
https://www.encodeproject.org/files/ENCFF357IXX/@@download/ENCFF357IXX.tsv
https://www.encodeproject.org/files/ENCFF717EVB/@@download/ENCFF717EVB.tsv
https://www.encodeproject.org/files/ENCFF427CHX/@@download/ENCFF427CHX.tsv
https://www.encodeproject.org/files/ENCFF026ELB/@@download/ENCFF026ELB.tsv
https://www.encodeproject.org/files/ENCFF817DQA/@@download/ENCFF817DQA.tsv
https://www.encodeproject.org/files/ENCFF470QTH/@@download/ENCFF470QTH.tsv
https://www.encodeproject.org/files/ENCFF793CXW/@@download/ENCFF793CXW.tsv
https://www.encodeproject.org/files/ENCFF391JRC/@@download/ENCFF391JRC.tsv
https://www.encodeproject.org/files/ENCFF520RQW/@@download/ENCFF520RQW.tsv
https://www.encodeproject.org/files/ENCFF923CZL/@@download/ENCFF923CZL.tsv
https://www.encodeproject.org/files/ENCFF269AFK/@@download/ENCFF269AFK.tsv
https://www.encodeproject.org/files/ENCFF057FSE/@@download/ENCFF057FSE.tsv
https://www.encodeproject.org/files/ENCFF855MSY/@@download/ENCFF855MSY.tsv
https://www.encodeproject.org/files/ENCFF896LEJ/@@download/ENCFF896LEJ.tsv
https://www.encodeproject.org/files/ENCFF259ROQ/@@download/ENCFF259ROQ.tsv
https://www.encodeproject.org/files/ENCFF707XJU/@@download/ENCFF707XJU.tsv
https://www.encodeproject.org/files/ENCFF136NBQ/@@download/ENCFF136NBQ.tsv
https://www.encodeproject.org/files/ENCFF837DUP/@@download/ENCFF837DUP.tsv
https://www.encodeproject.org/files/ENCFF401ZYO/@@download/ENCFF401ZYO.tsv
https://www.encodeproject.org/files/ENCFF459TEM/@@download/ENCFF459TEM.tsv
https://www.encodeproject.org/files/ENCFF569IPW/@@download/ENCFF569IPW.tsv
https://www.encodeproject.org/files/ENCFF045ALS/@@download/ENCFF045ALS.tsv
https://www.encodeproject.org/files/ENCFF876SQO/@@download/ENCFF876SQO.tsv
https://www.encodeproject.org/files/ENCFF999GOK/@@download/ENCFF999GOK.tsv
https://www.encodeproject.org/files/ENCFF458GUX/@@download/ENCFF458GUX.tsv
https://www.encodeproject.org/files/ENCFF745BOG/@@download/ENCFF745BOG.tsv
https://www.encodeproject.org/files/ENCFF410ZHD/@@download/ENCFF410ZHD.tsv
https://www.encodeproject.org/files/ENCFF729JYF/@@download/ENCFF729JYF.tsv
https://www.encodeproject.org/files/ENCFF519SMF/@@download/ENCFF519SMF.tsv
https://www.encodeproject.org/files/ENCFF966LVC/@@download/ENCFF966LVC.tsv
https://www.encodeproject.org/files/ENCFF056YLH/@@download/ENCFF056YLH.tsv
https://www.encodeproject.org/files/ENCFF031GWM/@@download/ENCFF031GWM.tsv
https://www.encodeproject.org/files/ENCFF648TBV/@@download/ENCFF648TBV.bed.gz
https://www.encodeproject.org/files/ENCFF126IQM/@@download/ENCFF126IQM.bed.gz
https://www.encodeproject.org/files/ENCFF193SAI/@@download/ENCFF193SAI.tsv
https://www.encodeproject.org/files/ENCFF841SRB/@@download/ENCFF841SRB.tsv
https://www.encodeproject.org/files/ENCFF924ZUX/@@download/ENCFF924ZUX.tsv
https://www.encodeproject.org/files/ENCFF135TEV/@@download/ENCFF135TEV.tsv
https://www.encodeproject.org/files/ENCFF485TKI/@@download/ENCFF485TKI.tsv
https://www.encodeproject.org/files/ENCFF872SLK/@@download/ENCFF872SLK.tsv
https://www.encodeproject.org/files/ENCFF170PGF/@@download/ENCFF170PGF.tsv
https://www.encodeproject.org/files/ENCFF715DIL/@@download/ENCFF715DIL.tsv
https://www.encodeproject.org/files/ENCFF346XPF/@@download/ENCFF346XPF.tsv
https://www.encodeproject.org/files/ENCFF574ANJ/@@download/ENCFF574ANJ.tsv
https://www.encodeproject.org/files/ENCFF813TVN/@@download/ENCFF813TVN.bed.gz
https://www.encodeproject.org/files/ENCFF298QFN/@@download/ENCFF298QFN.bed.gz
https://www.encodeproject.org/files/ENCFF117QKP/@@download/ENCFF117QKP.bed.gz
https://www.encodeproject.org/files/ENCFF134FRX/@@download/ENCFF134FRX.bed.gz
https://www.encodeproject.org/files/ENCFF262PXW/@@download/ENCFF262PXW.tsv
https://www.encodeproject.org/files/ENCFF422OAC/@@download/ENCFF422OAC.tsv
https://www.encodeproject.org/files/ENCFF029EII/@@download/ENCFF029EII.tsv
https://www.encodeproject.org/files/ENCFF941VVI/@@download/ENCFF941VVI.tsv
https://www.encodeproject.org/files/ENCFF864NMG/@@download/ENCFF864NMG.bed.gz
https://www.encodeproject.org/files/ENCFF293KBP/@@download/ENCFF293KBP.bed.gz
https://www.encodeproject.org/files/ENCFF688EDA/@@download/ENCFF688EDA.tsv
https://www.encodeproject.org/files/ENCFF581IOZ/@@download/ENCFF581IOZ.tsv
https://www.encodeproject.org/files/ENCFF179SVM/@@download/ENCFF179SVM.tsv
https://www.encodeproject.org/files/ENCFF106RWF/@@download/ENCFF106RWF.tsv
https://www.encodeproject.org/files/ENCFF894ONZ/@@download/ENCFF894ONZ.tsv
https://www.encodeproject.org/files/ENCFF268RKR/@@download/ENCFF268RKR.tsv
https://www.encodeproject.org/files/ENCFF564LBJ/@@download/ENCFF564LBJ.tsv
https://www.encodeproject.org/files/ENCFF669GAJ/@@download/ENCFF669GAJ.tsv
https://www.encodeproject.org/files/ENCFF319TDW/@@download/ENCFF319TDW.bed.gz
https://www.encodeproject.org/files/ENCFF544DRZ/@@download/ENCFF544DRZ.bed.gz
https://www.encodeproject.org/files/ENCFF715SQI/@@download/ENCFF715SQI.bed.gz
https://www.encodeproject.org/files/ENCFF083OIG/@@download/ENCFF083OIG.tsv
https://www.encodeproject.org/files/ENCFF456XDP/@@download/ENCFF456XDP.tsv
https://www.encodeproject.org/files/ENCFF465ZHS/@@download/ENCFF465ZHS.tsv
https://www.encodeproject.org/files/ENCFF388TRM/@@download/ENCFF388TRM.tsv
https://www.encodeproject.org/files/ENCFF193FIH/@@download/ENCFF193FIH.tsv
https://www.encodeproject.org/files/ENCFF842OMI/@@download/ENCFF842OMI.tsv
https://www.encodeproject.org/files/ENCFF762GOC/@@download/ENCFF762GOC.tsv
https://www.encodeproject.org/files/ENCFF351IBT/@@download/ENCFF351IBT.tsv
https://www.encodeproject.org/files/ENCFF293XMV/@@download/ENCFF293XMV.tsv
https://www.encodeproject.org/files/ENCFF835DNX/@@download/ENCFF835DNX.tsv
https://www.encodeproject.org/files/ENCFF409RJT/@@download/ENCFF409RJT.tsv
https://www.encodeproject.org/files/ENCFF031YEF/@@download/ENCFF031YEF.bed.gz
https://www.encodeproject.org/files/ENCFF907TLO/@@download/ENCFF907TLO.bed.gz
https://www.encodeproject.org/files/ENCFF512FTV/@@download/ENCFF512FTV.tsv
https://www.encodeproject.org/files/ENCFF784PCB/@@download/ENCFF784PCB.tsv
https://www.encodeproject.org/files/ENCFF605BSF/@@download/ENCFF605BSF.tsv
https://www.encodeproject.org/files/ENCFF978GME/@@download/ENCFF978GME.tsv
https://www.encodeproject.org/files/ENCFF297CFL/@@download/ENCFF297CFL.tsv
https://www.encodeproject.org/files/ENCFF306XAM/@@download/ENCFF306XAM.tsv
https://www.encodeproject.org/files/ENCFF961NLG/@@download/ENCFF961NLG.tsv
https://www.encodeproject.org/files/ENCFF223BBB/@@download/ENCFF223BBB.tsv
https://www.encodeproject.org/files/ENCFF861RBP/@@download/ENCFF861RBP.tsv
https://www.encodeproject.org/files/ENCFF505XEX/@@download/ENCFF505XEX.tsv
https://www.encodeproject.org/files/ENCFF407EVV/@@download/ENCFF407EVV.tsv
https://www.encodeproject.org/files/ENCFF618VDG/@@download/ENCFF618VDG.tsv
https://www.encodeproject.org/files/ENCFF899TEE/@@download/ENCFF899TEE.tsv
https://www.encodeproject.org/files/ENCFF819XJK/@@download/ENCFF819XJK.tsv
https://www.encodeproject.org/files/ENCFF814UBS/@@download/ENCFF814UBS.tsv
https://www.encodeproject.org/files/ENCFF915WEK/@@download/ENCFF915WEK.tsv
https://www.encodeproject.org/files/ENCFF079HPJ/@@download/ENCFF079HPJ.tsv
https://www.encodeproject.org/files/ENCFF863IMN/@@download/ENCFF863IMN.tsv
https://www.encodeproject.org/files/ENCFF179RZN/@@download/ENCFF179RZN.tsv
https://www.encodeproject.org/files/ENCFF891OQH/@@download/ENCFF891OQH.tsv
https://www.encodeproject.org/files/ENCFF528AXU/@@download/ENCFF528AXU.tsv
https://www.encodeproject.org/files/ENCFF641OAC/@@download/ENCFF641OAC.tsv
https://www.encodeproject.org/files/ENCFF421YBM/@@download/ENCFF421YBM.tsv
https://www.encodeproject.org/files/ENCFF915QBG/@@download/ENCFF915QBG.tsv
https://www.encodeproject.org/files/ENCFF938NUW/@@download/ENCFF938NUW.tsv
https://www.encodeproject.org/files/ENCFF823FZD/@@download/ENCFF823FZD.tsv
https://www.encodeproject.org/files/ENCFF089UZQ/@@download/ENCFF089UZQ.tsv
https://www.encodeproject.org/files/ENCFF661OOB/@@download/ENCFF661OOB.tsv
https://www.encodeproject.org/files/ENCFF902CGC/@@download/ENCFF902CGC.tsv
https://www.encodeproject.org/files/ENCFF173TII/@@download/ENCFF173TII.tsv
https://www.encodeproject.org/files/ENCFF214AFK/@@download/ENCFF214AFK.tsv
https://www.encodeproject.org/files/ENCFF841VGA/@@download/ENCFF841VGA.tsv
https://www.encodeproject.org/files/ENCFF716XQB/@@download/ENCFF716XQB.tsv
https://www.encodeproject.org/files/ENCFF345UKY/@@download/ENCFF345UKY.tsv
https://www.encodeproject.org/files/ENCFF498WEB/@@download/ENCFF498WEB.tsv
https://www.encodeproject.org/files/ENCFF991XEB/@@download/ENCFF991XEB.tsv
https://www.encodeproject.org/files/ENCFF738XZS/@@download/ENCFF738XZS.tsv
https://www.encodeproject.org/files/ENCFF340TEN/@@download/ENCFF340TEN.tsv
https://www.encodeproject.org/files/ENCFF335XEM/@@download/ENCFF335XEM.tsv
https://www.encodeproject.org/files/ENCFF272WRQ/@@download/ENCFF272WRQ.tsv
https://www.encodeproject.org/files/ENCFF437MWC/@@download/ENCFF437MWC.tsv
https://www.encodeproject.org/files/ENCFF566IZY/@@download/ENCFF566IZY.tsv
https://www.encodeproject.org/files/ENCFF946LWT/@@download/ENCFF946LWT.tsv
https://www.encodeproject.org/files/ENCFF957CWU/@@download/ENCFF957CWU.tsv
https://www.encodeproject.org/files/ENCFF356YQN/@@download/ENCFF356YQN.tsv
https://www.encodeproject.org/files/ENCFF452MVU/@@download/ENCFF452MVU.tsv
https://www.encodeproject.org/files/ENCFF940HAL/@@download/ENCFF940HAL.tsv
https://www.encodeproject.org/files/ENCFF222QKD/@@download/ENCFF222QKD.tsv
https://www.encodeproject.org/files/ENCFF201LSJ/@@download/ENCFF201LSJ.tsv
https://www.encodeproject.org/files/ENCFF381XVS/@@download/ENCFF381XVS.tsv
https://www.encodeproject.org/files/ENCFF318LUZ/@@download/ENCFF318LUZ.tsv
https://www.encodeproject.org/files/ENCFF679ZFQ/@@download/ENCFF679ZFQ.tsv
https://www.encodeproject.org/files/ENCFF242VUG/@@download/ENCFF242VUG.tsv
https://www.encodeproject.org/files/ENCFF189BHW/@@download/ENCFF189BHW.tsv
https://www.encodeproject.org/files/ENCFF794XEZ/@@download/ENCFF794XEZ.tsv
https://www.encodeproject.org/files/ENCFF669QAC/@@download/ENCFF669QAC.tsv
https://www.encodeproject.org/files/ENCFF389PPC/@@download/ENCFF389PPC.tsv
https://www.encodeproject.org/files/ENCFF278ECV/@@download/ENCFF278ECV.tsv
https://www.encodeproject.org/files/ENCFF083WIC/@@download/ENCFF083WIC.tsv
https://www.encodeproject.org/files/ENCFF763MIF/@@download/ENCFF763MIF.tsv
https://www.encodeproject.org/files/ENCFF087FIC/@@download/ENCFF087FIC.tsv
https://www.encodeproject.org/files/ENCFF762NVQ/@@download/ENCFF762NVQ.tsv
https://www.encodeproject.org/files/ENCFF804ETQ/@@download/ENCFF804ETQ.tsv
https://www.encodeproject.org/files/ENCFF511LJA/@@download/ENCFF511LJA.tsv
https://www.encodeproject.org/files/ENCFF827ILK/@@download/ENCFF827ILK.tsv
https://www.encodeproject.org/files/ENCFF245MDF/@@download/ENCFF245MDF.tsv
https://www.encodeproject.org/files/ENCFF510XIS/@@download/ENCFF510XIS.tsv
https://www.encodeproject.org/files/ENCFF694JSN/@@download/ENCFF694JSN.tsv
https://www.encodeproject.org/files/ENCFF472AJZ/@@download/ENCFF472AJZ.tsv
https://www.encodeproject.org/files/ENCFF845KBZ/@@download/ENCFF845KBZ.tsv
https://www.encodeproject.org/files/ENCFF525ZWW/@@download/ENCFF525ZWW.tsv
https://www.encodeproject.org/files/ENCFF951HUV/@@download/ENCFF951HUV.tsv
https://www.encodeproject.org/files/ENCFF152EYR/@@download/ENCFF152EYR.tsv
https://www.encodeproject.org/files/ENCFF063FIR/@@download/ENCFF063FIR.tsv
https://www.encodeproject.org/files/ENCFF518BOX/@@download/ENCFF518BOX.tsv
https://www.encodeproject.org/files/ENCFF388BGA/@@download/ENCFF388BGA.tsv
https://www.encodeproject.org/files/ENCFF416XQG/@@download/ENCFF416XQG.tsv
https://www.encodeproject.org/files/ENCFF371MAZ/@@download/ENCFF371MAZ.tsv
https://www.encodeproject.org/files/ENCFF027LSJ/@@download/ENCFF027LSJ.tsv
https://www.encodeproject.org/files/ENCFF455EZQ/@@download/ENCFF455EZQ.tsv
https://www.encodeproject.org/files/ENCFF681AZG/@@download/ENCFF681AZG.tsv
https://www.encodeproject.org/files/ENCFF002DEA/@@download/ENCFF002DEA.tsv
https://www.encodeproject.org/files/ENCFF002DEB/@@download/ENCFF002DEB.tsv
https://www.encodeproject.org/files/ENCFF002DEC/@@download/ENCFF002DEC.tsv
https://www.encodeproject.org/files/ENCFF232CHY/@@download/ENCFF232CHY.tsv
https://www.encodeproject.org/files/ENCFF157MJN/@@download/ENCFF157MJN.tsv
https://www.encodeproject.org/files/ENCFF493XXL/@@download/ENCFF493XXL.tsv
https://www.encodeproject.org/files/ENCFF749TMN/@@download/ENCFF749TMN.bed.gz
https://www.encodeproject.org/files/ENCFF795EZC/@@download/ENCFF795EZC.bed.gz
https://www.encodeproject.org/files/ENCFF002DFE/@@download/ENCFF002DFE.tsv
https://www.encodeproject.org/files/ENCFF002DFF/@@download/ENCFF002DFF.tsv
https://www.encodeproject.org/files/ENCFF002DFG/@@download/ENCFF002DFG.tsv
https://www.encodeproject.org/files/ENCFF499CES/@@download/ENCFF499CES.bed.gz
https://www.encodeproject.org/files/ENCFF832GIY/@@download/ENCFF832GIY.bed.gz
https://www.encodeproject.org/files/ENCFF784JYD/@@download/ENCFF784JYD.tsv
https://www.encodeproject.org/files/ENCFF189NSX/@@download/ENCFF189NSX.tsv
https://www.encodeproject.org/files/ENCFF799ZVX/@@download/ENCFF799ZVX.tsv
https://www.encodeproject.org/files/ENCFF003NMX/@@download/ENCFF003NMX.tsv
https://www.encodeproject.org/files/ENCFF572WPM/@@download/ENCFF572WPM.tsv
https://www.encodeproject.org/files/ENCFF105LNF/@@download/ENCFF105LNF.tsv
https://www.encodeproject.org/files/ENCFF410FBU/@@download/ENCFF410FBU.tsv
https://www.encodeproject.org/files/ENCFF691NQF/@@download/ENCFF691NQF.tsv
https://www.encodeproject.org/files/ENCFF291WEC/@@download/ENCFF291WEC.tsv
https://www.encodeproject.org/files/ENCFF497RAZ/@@download/ENCFF497RAZ.tsv
https://www.encodeproject.org/files/ENCFF935NYJ/@@download/ENCFF935NYJ.tsv
https://www.encodeproject.org/files/ENCFF009LID/@@download/ENCFF009LID.tsv
https://www.encodeproject.org/files/ENCFF073URD/@@download/ENCFF073URD.tsv
https://www.encodeproject.org/files/ENCFF265BIN/@@download/ENCFF265BIN.tsv
https://www.encodeproject.org/files/ENCFF791XTX/@@download/ENCFF791XTX.tsv
https://www.encodeproject.org/files/ENCFF684NKR/@@download/ENCFF684NKR.tsv
https://www.encodeproject.org/files/ENCFF726HDC/@@download/ENCFF726HDC.tsv
https://www.encodeproject.org/files/ENCFF002DEG/@@download/ENCFF002DEG.tsv
https://www.encodeproject.org/files/ENCFF002DEH/@@download/ENCFF002DEH.tsv
https://www.encodeproject.org/files/ENCFF002DEI/@@download/ENCFF002DEI.tsv
https://www.encodeproject.org/files/ENCFF002EVE/@@download/ENCFF002EVE.tsv
https://www.encodeproject.org/files/ENCFF002EVF/@@download/ENCFF002EVF.tsv
https://www.encodeproject.org/files/ENCFF002EVI/@@download/ENCFF002EVI.tsv
https://www.encodeproject.org/files/ENCFF817UKQ/@@download/ENCFF817UKQ.bed.gz
https://www.encodeproject.org/files/ENCFF988VZT/@@download/ENCFF988VZT.bed.gz
https://www.encodeproject.org/files/ENCFF621BGN/@@download/ENCFF621BGN.tsv
https://www.encodeproject.org/files/ENCFF820GEE/@@download/ENCFF820GEE.tsv
https://www.encodeproject.org/files/ENCFF431TKD/@@download/ENCFF431TKD.tsv
https://www.encodeproject.org/files/ENCFF260EGH/@@download/ENCFF260EGH.tsv
https://www.encodeproject.org/files/ENCFF792ROS/@@download/ENCFF792ROS.tsv
https://www.encodeproject.org/files/ENCFF083LIF/@@download/ENCFF083LIF.tsv
https://www.encodeproject.org/files/ENCFF140TLP/@@download/ENCFF140TLP.tsv
https://www.encodeproject.org/files/ENCFF661BCA/@@download/ENCFF661BCA.tsv
https://www.encodeproject.org/files/ENCFF756ZGX/@@download/ENCFF756ZGX.tsv
https://www.encodeproject.org/files/ENCFF102BFN/@@download/ENCFF102BFN.tsv
https://www.encodeproject.org/files/ENCFF190ZRO/@@download/ENCFF190ZRO.tsv
https://www.encodeproject.org/files/ENCFF156RLV/@@download/ENCFF156RLV.tsv
https://www.encodeproject.org/files/ENCFF473SQY/@@download/ENCFF473SQY.tsv
https://www.encodeproject.org/files/ENCFF745KUY/@@download/ENCFF745KUY.tsv
https://www.encodeproject.org/files/ENCFF487PLP/@@download/ENCFF487PLP.tsv
https://www.encodeproject.org/files/ENCFF884AFI/@@download/ENCFF884AFI.tsv
https://www.encodeproject.org/files/ENCFF313SEU/@@download/ENCFF313SEU.tsv
https://www.encodeproject.org/files/ENCFF632XWC/@@download/ENCFF632XWC.tsv
https://www.encodeproject.org/files/ENCFF796QEY/@@download/ENCFF796QEY.tsv
https://www.encodeproject.org/files/ENCFF194JNW/@@download/ENCFF194JNW.tsv
https://www.encodeproject.org/files/ENCFF093XSA/@@download/ENCFF093XSA.bed.gz
https://www.encodeproject.org/files/ENCFF937RMQ/@@download/ENCFF937RMQ.bed.gz
https://www.encodeproject.org/files/ENCFF446BRC/@@download/ENCFF446BRC.tsv
https://www.encodeproject.org/files/ENCFF359JRV/@@download/ENCFF359JRV.tsv
https://www.encodeproject.org/files/ENCFF841MFA/@@download/ENCFF841MFA.tsv
https://www.encodeproject.org/files/ENCFF556SJQ/@@download/ENCFF556SJQ.bed.gz
https://www.encodeproject.org/files/ENCFF415RLT/@@download/ENCFF415RLT.tsv
https://www.encodeproject.org/files/ENCFF826BAQ/@@download/ENCFF826BAQ.tsv
https://www.encodeproject.org/files/ENCFF891TDY/@@download/ENCFF891TDY.tsv
https://www.encodeproject.org/files/ENCFF610YNE/@@download/ENCFF610YNE.tsv
https://www.encodeproject.org/files/ENCFF325TXM/@@download/ENCFF325TXM.bed.gz
https://www.encodeproject.org/files/ENCFF464UVC/@@download/ENCFF464UVC.bed.gz
https://www.encodeproject.org/files/ENCFF712ZAK/@@download/ENCFF712ZAK.bed.gz
https://www.encodeproject.org/files/ENCFF356DWW/@@download/ENCFF356DWW.tsv
https://www.encodeproject.org/files/ENCFF924TSO/@@download/ENCFF924TSO.tsv
https://www.encodeproject.org/files/ENCFF757NUT/@@download/ENCFF757NUT.tsv
https://www.encodeproject.org/files/ENCFF865YVO/@@download/ENCFF865YVO.tsv
https://www.encodeproject.org/files/ENCFF631TWR/@@download/ENCFF631TWR.tsv
https://www.encodeproject.org/files/ENCFF146LBG/@@download/ENCFF146LBG.tsv
https://www.encodeproject.org/files/ENCFF619SGN/@@download/ENCFF619SGN.tsv
https://www.encodeproject.org/files/ENCFF193EMA/@@download/ENCFF193EMA.tsv
https://www.encodeproject.org/files/ENCFF735TCL/@@download/ENCFF735TCL.tsv
https://www.encodeproject.org/files/ENCFF170BKQ/@@download/ENCFF170BKQ.tsv
https://www.encodeproject.org/files/ENCFF522CPG/@@download/ENCFF522CPG.tsv
https://www.encodeproject.org/files/ENCFF672ZPY/@@download/ENCFF672ZPY.tsv
https://www.encodeproject.org/files/ENCFF943MNY/@@download/ENCFF943MNY.tsv
https://www.encodeproject.org/files/ENCFF921OBL/@@download/ENCFF921OBL.tsv
https://www.encodeproject.org/files/ENCFF902SNR/@@download/ENCFF902SNR.tsv
https://www.encodeproject.org/files/ENCFF259WWZ/@@download/ENCFF259WWZ.tsv
https://www.encodeproject.org/files/ENCFF588INN/@@download/ENCFF588INN.tsv
https://www.encodeproject.org/files/ENCFF078JLK/@@download/ENCFF078JLK.tsv
https://www.encodeproject.org/files/ENCFF975CXE/@@download/ENCFF975CXE.tsv
https://www.encodeproject.org/files/ENCFF390FGE/@@download/ENCFF390FGE.bed.gz
https://www.encodeproject.org/files/ENCFF749PUO/@@download/ENCFF749PUO.tsv
https://www.encodeproject.org/files/ENCFF285OLQ/@@download/ENCFF285OLQ.tsv
https://www.encodeproject.org/files/ENCFF359PFB/@@download/ENCFF359PFB.tsv
https://www.encodeproject.org/files/ENCFF822GML/@@download/ENCFF822GML.tsv
https://www.encodeproject.org/files/ENCFF200ERL/@@download/ENCFF200ERL.tsv
https://www.encodeproject.org/files/ENCFF701XPF/@@download/ENCFF701XPF.tsv
https://www.encodeproject.org/files/ENCFF506LTL/@@download/ENCFF506LTL.tsv
https://www.encodeproject.org/files/ENCFF171TZH/@@download/ENCFF171TZH.tsv
https://www.encodeproject.org/files/ENCFF589AOW/@@download/ENCFF589AOW.tsv
https://www.encodeproject.org/files/ENCFF364MOL/@@download/ENCFF364MOL.tsv
https://www.encodeproject.org/files/ENCFF100OEJ/@@download/ENCFF100OEJ.tsv
https://www.encodeproject.org/files/ENCFF283ODT/@@download/ENCFF283ODT.bed.gz
https://www.encodeproject.org/files/ENCFF951WED/@@download/ENCFF951WED.tsv
https://www.encodeproject.org/files/ENCFF852RPM/@@download/ENCFF852RPM.tsv
https://www.encodeproject.org/files/ENCFF765KER/@@download/ENCFF765KER.tsv
https://www.encodeproject.org/files/ENCFF592FMJ/@@download/ENCFF592FMJ.tsv
https://www.encodeproject.org/files/ENCFF266NJN/@@download/ENCFF266NJN.tsv
https://www.encodeproject.org/files/ENCFF380JJG/@@download/ENCFF380JJG.tsv
https://www.encodeproject.org/files/ENCFF910BCQ/@@download/ENCFF910BCQ.bed.gz
https://www.encodeproject.org/files/ENCFF370OUE/@@download/ENCFF370OUE.bed.gz
https://www.encodeproject.org/files/ENCFF108IBF/@@download/ENCFF108IBF.tsv
https://www.encodeproject.org/files/ENCFF536WVL/@@download/ENCFF536WVL.tsv
https://www.encodeproject.org/files/ENCFF952BVQ/@@download/ENCFF952BVQ.tsv
https://www.encodeproject.org/files/ENCFF111IQQ/@@download/ENCFF111IQQ.tsv
https://www.encodeproject.org/files/ENCFF185UAE/@@download/ENCFF185UAE.tsv
https://www.encodeproject.org/files/ENCFF975KOB/@@download/ENCFF975KOB.tsv
https://www.encodeproject.org/files/ENCFF298ZWZ/@@download/ENCFF298ZWZ.tsv
https://www.encodeproject.org/files/ENCFF166TCK/@@download/ENCFF166TCK.tsv
https://www.encodeproject.org/files/ENCFF518QQO/@@download/ENCFF518QQO.tsv
https://www.encodeproject.org/files/ENCFF131QFS/@@download/ENCFF131QFS.tsv
https://www.encodeproject.org/files/ENCFF081SZX/@@download/ENCFF081SZX.tsv
https://www.encodeproject.org/files/ENCFF808FRG/@@download/ENCFF808FRG.tsv
https://www.encodeproject.org/files/ENCFF349NQV/@@download/ENCFF349NQV.bed.gz
https://www.encodeproject.org/files/ENCFF234GJL/@@download/ENCFF234GJL.tsv
https://www.encodeproject.org/files/ENCFF890ORL/@@download/ENCFF890ORL.tsv
https://www.encodeproject.org/files/ENCFF360OVB/@@download/ENCFF360OVB.tsv
https://www.encodeproject.org/files/ENCFF494LLV/@@download/ENCFF494LLV.tsv
https://www.encodeproject.org/files/ENCFF728KCD/@@download/ENCFF728KCD.bed.gz
https://www.encodeproject.org/files/ENCFF198OFN/@@download/ENCFF198OFN.tsv
https://www.encodeproject.org/files/ENCFF729OVU/@@download/ENCFF729OVU.tsv
https://www.encodeproject.org/files/ENCFF833TOX/@@download/ENCFF833TOX.tsv
https://www.encodeproject.org/files/ENCFF514HLE/@@download/ENCFF514HLE.tsv
https://www.encodeproject.org/files/ENCFF139WJC/@@download/ENCFF139WJC.tsv
https://www.encodeproject.org/files/ENCFF446PHG/@@download/ENCFF446PHG.tsv
https://www.encodeproject.org/files/ENCFF388UFE/@@download/ENCFF388UFE.tsv
https://www.encodeproject.org/files/ENCFF051YRS/@@download/ENCFF051YRS.tsv
https://www.encodeproject.org/files/ENCFF221RQV/@@download/ENCFF221RQV.tsv
https://www.encodeproject.org/files/ENCFF183CKH/@@download/ENCFF183CKH.tsv
https://www.encodeproject.org/files/ENCFF842JHX/@@download/ENCFF842JHX.tsv
https://www.encodeproject.org/files/ENCFF495WZV/@@download/ENCFF495WZV.tsv
https://www.encodeproject.org/files/ENCFF351RRP/@@download/ENCFF351RRP.tsv
https://www.encodeproject.org/files/ENCFF879MFV/@@download/ENCFF879MFV.tsv
https://www.encodeproject.org/files/ENCFF971NRM/@@download/ENCFF971NRM.tsv
https://www.encodeproject.org/files/ENCFF191NLM/@@download/ENCFF191NLM.tsv
https://www.encodeproject.org/files/ENCFF015CJR/@@download/ENCFF015CJR.bed.gz
https://www.encodeproject.org/files/ENCFF425CRZ/@@download/ENCFF425CRZ.bed.gz
https://www.encodeproject.org/files/ENCFF484TAR/@@download/ENCFF484TAR.tsv
https://www.encodeproject.org/files/ENCFF979SDN/@@download/ENCFF979SDN.tsv
https://www.encodeproject.org/files/ENCFF769CCM/@@download/ENCFF769CCM.tsv
https://www.encodeproject.org/files/ENCFF022PDN/@@download/ENCFF022PDN.tsv
https://www.encodeproject.org/files/ENCFF878HMC/@@download/ENCFF878HMC.bed.gz
https://www.encodeproject.org/files/ENCFF214NXF/@@download/ENCFF214NXF.tsv
https://www.encodeproject.org/files/ENCFF529RME/@@download/ENCFF529RME.tsv
https://www.encodeproject.org/files/ENCFF810PLU/@@download/ENCFF810PLU.tsv
https://www.encodeproject.org/files/ENCFF150OOG/@@download/ENCFF150OOG.tsv
https://www.encodeproject.org/files/ENCFF612PCY/@@download/ENCFF612PCY.tsv
https://www.encodeproject.org/files/ENCFF793PCZ/@@download/ENCFF793PCZ.tsv
https://www.encodeproject.org/files/ENCFF191CTZ/@@download/ENCFF191CTZ.tsv
https://www.encodeproject.org/files/ENCFF396JVK/@@download/ENCFF396JVK.bed.gz
https://www.encodeproject.org/files/ENCFF083UGT/@@download/ENCFF083UGT.tsv
https://www.encodeproject.org/files/ENCFF409BQS/@@download/ENCFF409BQS.tsv
https://www.encodeproject.org/files/ENCFF047JVW/@@download/ENCFF047JVW.tsv
https://www.encodeproject.org/files/ENCFF310LNQ/@@download/ENCFF310LNQ.tsv
https://www.encodeproject.org/files/ENCFF196LGM/@@download/ENCFF196LGM.tsv
https://www.encodeproject.org/files/ENCFF519MEJ/@@download/ENCFF519MEJ.tsv
https://www.encodeproject.org/files/ENCFF749OEM/@@download/ENCFF749OEM.tsv
https://www.encodeproject.org/files/ENCFF953ZVW/@@download/ENCFF953ZVW.tsv
https://www.encodeproject.org/files/ENCFF639XVL/@@download/ENCFF639XVL.tsv
https://www.encodeproject.org/files/ENCFF063VIP/@@download/ENCFF063VIP.tsv
https://www.encodeproject.org/files/ENCFF995ECH/@@download/ENCFF995ECH.tsv
https://www.encodeproject.org/files/ENCFF045VHV/@@download/ENCFF045VHV.tsv
https://www.encodeproject.org/files/ENCFF753JLV/@@download/ENCFF753JLV.tsv
https://www.encodeproject.org/files/ENCFF408CLJ/@@download/ENCFF408CLJ.tsv
https://www.encodeproject.org/files/ENCFF846RCG/@@download/ENCFF846RCG.tsv
https://www.encodeproject.org/files/ENCFF747KCB/@@download/ENCFF747KCB.tsv
https://www.encodeproject.org/files/ENCFF913VDL/@@download/ENCFF913VDL.tsv
https://www.encodeproject.org/files/ENCFF866ZOH/@@download/ENCFF866ZOH.tsv
https://www.encodeproject.org/files/ENCFF458NWK/@@download/ENCFF458NWK.tsv
https://www.encodeproject.org/files/ENCFF671UIN/@@download/ENCFF671UIN.tsv
https://www.encodeproject.org/files/ENCFF065BGK/@@download/ENCFF065BGK.tsv
https://www.encodeproject.org/files/ENCFF628ZQW/@@download/ENCFF628ZQW.tsv
https://www.encodeproject.org/files/ENCFF283LHM/@@download/ENCFF283LHM.tsv
https://www.encodeproject.org/files/ENCFF991VQM/@@download/ENCFF991VQM.tsv
https://www.encodeproject.org/files/ENCFF056BZQ/@@download/ENCFF056BZQ.tsv
https://www.encodeproject.org/files/ENCFF074EJA/@@download/ENCFF074EJA.tsv
https://www.encodeproject.org/files/ENCFF037VRZ/@@download/ENCFF037VRZ.tsv
https://www.encodeproject.org/files/ENCFF291ILD/@@download/ENCFF291ILD.tsv
https://www.encodeproject.org/files/ENCFF771KFR/@@download/ENCFF771KFR.tsv
https://www.encodeproject.org/files/ENCFF264SDW/@@download/ENCFF264SDW.tsv
https://www.encodeproject.org/files/ENCFF272RPE/@@download/ENCFF272RPE.tsv
https://www.encodeproject.org/files/ENCFF154BUE/@@download/ENCFF154BUE.tsv
https://www.encodeproject.org/files/ENCFF647DAZ/@@download/ENCFF647DAZ.tsv
https://www.encodeproject.org/files/ENCFF492NKP/@@download/ENCFF492NKP.tsv
https://www.encodeproject.org/files/ENCFF373IHG/@@download/ENCFF373IHG.tsv
https://www.encodeproject.org/files/ENCFF984XGE/@@download/ENCFF984XGE.tsv
https://www.encodeproject.org/files/ENCFF466EQG/@@download/ENCFF466EQG.tsv
https://www.encodeproject.org/files/ENCFF744ZDN/@@download/ENCFF744ZDN.tsv
https://www.encodeproject.org/files/ENCFF688ATJ/@@download/ENCFF688ATJ.tsv
https://www.encodeproject.org/files/ENCFF672EUE/@@download/ENCFF672EUE.tsv
https://www.encodeproject.org/files/ENCFF626WPP/@@download/ENCFF626WPP.tsv
https://www.encodeproject.org/files/ENCFF541BLM/@@download/ENCFF541BLM.tsv
https://www.encodeproject.org/files/ENCFF372WVS/@@download/ENCFF372WVS.tsv
https://www.encodeproject.org/files/ENCFF314LDN/@@download/ENCFF314LDN.tsv
https://www.encodeproject.org/files/ENCFF074YRT/@@download/ENCFF074YRT.tsv
https://www.encodeproject.org/files/ENCFF223UQZ/@@download/ENCFF223UQZ.tsv
https://www.encodeproject.org/files/ENCFF554UMM/@@download/ENCFF554UMM.tsv
https://www.encodeproject.org/files/ENCFF973JIY/@@download/ENCFF973JIY.tsv
https://www.encodeproject.org/files/ENCFF174NLG/@@download/ENCFF174NLG.tsv
https://www.encodeproject.org/files/ENCFF232FXD/@@download/ENCFF232FXD.tsv
https://www.encodeproject.org/files/ENCFF315DBD/@@download/ENCFF315DBD.tsv
https://www.encodeproject.org/files/ENCFF848YLS/@@download/ENCFF848YLS.tsv
https://www.encodeproject.org/files/ENCFF275UGA/@@download/ENCFF275UGA.tsv
https://www.encodeproject.org/files/ENCFF453IBG/@@download/ENCFF453IBG.tsv
https://www.encodeproject.org/files/ENCFF311UQL/@@download/ENCFF311UQL.tsv
https://www.encodeproject.org/files/ENCFF782DRP/@@download/ENCFF782DRP.tsv
https://www.encodeproject.org/files/ENCFF717ZBX/@@download/ENCFF717ZBX.tsv
https://www.encodeproject.org/files/ENCFF523UNS/@@download/ENCFF523UNS.tsv
https://www.encodeproject.org/files/ENCFF697NMB/@@download/ENCFF697NMB.tsv
https://www.encodeproject.org/files/ENCFF835OYI/@@download/ENCFF835OYI.tsv
https://www.encodeproject.org/files/ENCFF657EGF/@@download/ENCFF657EGF.tsv
https://www.encodeproject.org/files/ENCFF953ZVY/@@download/ENCFF953ZVY.tsv
https://www.encodeproject.org/files/ENCFF666GNP/@@download/ENCFF666GNP.tsv
https://www.encodeproject.org/files/ENCFF591ONJ/@@download/ENCFF591ONJ.tsv
https://www.encodeproject.org/files/ENCFF985YKH/@@download/ENCFF985YKH.tsv
https://www.encodeproject.org/files/ENCFF810PMV/@@download/ENCFF810PMV.tsv
https://www.encodeproject.org/files/ENCFF346EHH/@@download/ENCFF346EHH.tsv
https://www.encodeproject.org/files/ENCFF266UEH/@@download/ENCFF266UEH.tsv
https://www.encodeproject.org/files/ENCFF611VZL/@@download/ENCFF611VZL.tsv
https://www.encodeproject.org/files/ENCFF300YSL/@@download/ENCFF300YSL.tsv
https://www.encodeproject.org/files/ENCFF681UBK/@@download/ENCFF681UBK.tsv
https://www.encodeproject.org/files/ENCFF825PGJ/@@download/ENCFF825PGJ.tsv
https://www.encodeproject.org/files/ENCFF584TIL/@@download/ENCFF584TIL.tsv
https://www.encodeproject.org/files/ENCFF715YCE/@@download/ENCFF715YCE.tsv
https://www.encodeproject.org/files/ENCFF260DKM/@@download/ENCFF260DKM.tsv
https://www.encodeproject.org/files/ENCFF071SHP/@@download/ENCFF071SHP.tsv
https://www.encodeproject.org/files/ENCFF782LNG/@@download/ENCFF782LNG.tsv
https://www.encodeproject.org/files/ENCFF216DXM/@@download/ENCFF216DXM.tsv
https://www.encodeproject.org/files/ENCFF476FRC/@@download/ENCFF476FRC.tsv
https://www.encodeproject.org/files/ENCFF131HMZ/@@download/ENCFF131HMZ.tsv
https://www.encodeproject.org/files/ENCFF532AGU/@@download/ENCFF532AGU.tsv
https://www.encodeproject.org/files/ENCFF779EOH/@@download/ENCFF779EOH.tsv
https://www.encodeproject.org/files/ENCFF071ZPB/@@download/ENCFF071ZPB.tsv
https://www.encodeproject.org/files/ENCFF862KWY/@@download/ENCFF862KWY.tsv
https://www.encodeproject.org/files/ENCFF882SPJ/@@download/ENCFF882SPJ.tsv
https://www.encodeproject.org/files/ENCFF250NYG/@@download/ENCFF250NYG.tsv
https://www.encodeproject.org/files/ENCFF718QMF/@@download/ENCFF718QMF.tsv
https://www.encodeproject.org/files/ENCFF787TMW/@@download/ENCFF787TMW.tsv
https://www.encodeproject.org/files/ENCFF617KGP/@@download/ENCFF617KGP.tsv
https://www.encodeproject.org/files/ENCFF497QML/@@download/ENCFF497QML.tsv
https://www.encodeproject.org/files/ENCFF157IWY/@@download/ENCFF157IWY.tsv
https://www.encodeproject.org/files/ENCFF539CUI/@@download/ENCFF539CUI.tsv
https://www.encodeproject.org/files/ENCFF577HCJ/@@download/ENCFF577HCJ.tsv
https://www.encodeproject.org/files/ENCFF113HZK/@@download/ENCFF113HZK.tsv
https://www.encodeproject.org/files/ENCFF241MOO/@@download/ENCFF241MOO.tsv
https://www.encodeproject.org/files/ENCFF121DTB/@@download/ENCFF121DTB.tsv
https://www.encodeproject.org/files/ENCFF170CFD/@@download/ENCFF170CFD.tsv
https://www.encodeproject.org/files/ENCFF324AVV/@@download/ENCFF324AVV.tsv
https://www.encodeproject.org/files/ENCFF723LYO/@@download/ENCFF723LYO.tsv
https://www.encodeproject.org/files/ENCFF604EQA/@@download/ENCFF604EQA.tsv
https://www.encodeproject.org/files/ENCFF139RKR/@@download/ENCFF139RKR.tsv
https://www.encodeproject.org/files/ENCFF425QVN/@@download/ENCFF425QVN.tsv
https://www.encodeproject.org/files/ENCFF083AMW/@@download/ENCFF083AMW.tsv
https://www.encodeproject.org/files/ENCFF891JJG/@@download/ENCFF891JJG.tsv
https://www.encodeproject.org/files/ENCFF412ANC/@@download/ENCFF412ANC.tsv
https://www.encodeproject.org/files/ENCFF982MXY/@@download/ENCFF982MXY.tsv
https://www.encodeproject.org/files/ENCFF111GEB/@@download/ENCFF111GEB.tsv
https://www.encodeproject.org/files/ENCFF491LXQ/@@download/ENCFF491LXQ.tsv
https://www.encodeproject.org/files/ENCFF615JNZ/@@download/ENCFF615JNZ.tsv
https://www.encodeproject.org/files/ENCFF560ONY/@@download/ENCFF560ONY.tsv
https://www.encodeproject.org/files/ENCFF890AXZ/@@download/ENCFF890AXZ.tsv
https://www.encodeproject.org/files/ENCFF349ZGB/@@download/ENCFF349ZGB.tsv
https://www.encodeproject.org/files/ENCFF625QSH/@@download/ENCFF625QSH.tsv
https://www.encodeproject.org/files/ENCFF090VNK/@@download/ENCFF090VNK.tsv
https://www.encodeproject.org/files/ENCFF749DDH/@@download/ENCFF749DDH.tsv
https://www.encodeproject.org/files/ENCFF576WAA/@@download/ENCFF576WAA.tsv
https://www.encodeproject.org/files/ENCFF015VSF/@@download/ENCFF015VSF.tsv
https://www.encodeproject.org/files/ENCFF072KMO/@@download/ENCFF072KMO.tsv
https://www.encodeproject.org/files/ENCFF732SOC/@@download/ENCFF732SOC.tsv
https://www.encodeproject.org/files/ENCFF690SCB/@@download/ENCFF690SCB.tsv
https://www.encodeproject.org/files/ENCFF610RRA/@@download/ENCFF610RRA.tsv
https://www.encodeproject.org/files/ENCFF167KBI/@@download/ENCFF167KBI.tsv
https://www.encodeproject.org/files/ENCFF576NTR/@@download/ENCFF576NTR.tsv
https://www.encodeproject.org/files/ENCFF662VJZ/@@download/ENCFF662VJZ.tsv
https://www.encodeproject.org/files/ENCFF881QIB/@@download/ENCFF881QIB.tsv
https://www.encodeproject.org/files/ENCFF620GLE/@@download/ENCFF620GLE.tsv
https://www.encodeproject.org/files/ENCFF635SCW/@@download/ENCFF635SCW.tsv
https://www.encodeproject.org/files/ENCFF915OWQ/@@download/ENCFF915OWQ.tsv
https://www.encodeproject.org/files/ENCFF820ODU/@@download/ENCFF820ODU.tsv
https://www.encodeproject.org/files/ENCFF117RDG/@@download/ENCFF117RDG.tsv
https://www.encodeproject.org/files/ENCFF185NKV/@@download/ENCFF185NKV.bed.gz
https://www.encodeproject.org/files/ENCFF794MIP/@@download/ENCFF794MIP.bed.gz
https://www.encodeproject.org/files/ENCFF002DEM/@@download/ENCFF002DEM.tsv
https://www.encodeproject.org/files/ENCFF002DEN/@@download/ENCFF002DEN.tsv
https://www.encodeproject.org/files/ENCFF002DEO/@@download/ENCFF002DEO.tsv
https://www.encodeproject.org/files/ENCFF112DCJ/@@download/ENCFF112DCJ.tsv
https://www.encodeproject.org/files/ENCFF092FJB/@@download/ENCFF092FJB.tsv
https://www.encodeproject.org/files/ENCFF290JKE/@@download/ENCFF290JKE.tsv
https://www.encodeproject.org/files/ENCFF397EFW/@@download/ENCFF397EFW.tsv
https://www.encodeproject.org/files/ENCFF337UFE/@@download/ENCFF337UFE.tsv
https://www.encodeproject.org/files/ENCFF920TGK/@@download/ENCFF920TGK.tsv
https://www.encodeproject.org/files/ENCFF400IEP/@@download/ENCFF400IEP.tsv
https://www.encodeproject.org/files/ENCFF259EWN/@@download/ENCFF259EWN.tsv
https://www.encodeproject.org/files/ENCFF755RTG/@@download/ENCFF755RTG.tsv
https://www.encodeproject.org/files/ENCFF455VOQ/@@download/ENCFF455VOQ.tsv
https://www.encodeproject.org/files/ENCFF860CDY/@@download/ENCFF860CDY.tsv
https://www.encodeproject.org/files/ENCFF504GWV/@@download/ENCFF504GWV.tsv
https://www.encodeproject.org/files/ENCFF257EQJ/@@download/ENCFF257EQJ.tsv
https://www.encodeproject.org/files/ENCFF900EPD/@@download/ENCFF900EPD.tsv
https://www.encodeproject.org/files/ENCFF573MYB/@@download/ENCFF573MYB.tsv
https://www.encodeproject.org/files/ENCFF002DEY/@@download/ENCFF002DEY.tsv
https://www.encodeproject.org/files/ENCFF002DEZ/@@download/ENCFF002DEZ.tsv
https://www.encodeproject.org/files/ENCFF002DFA/@@download/ENCFF002DFA.tsv
https://www.encodeproject.org/files/ENCFF085TLW/@@download/ENCFF085TLW.tsv
https://www.encodeproject.org/files/ENCFF056ZFM/@@download/ENCFF056ZFM.tsv
https://www.encodeproject.org/files/ENCFF971PUI/@@download/ENCFF971PUI.tsv
https://www.encodeproject.org/files/ENCFF612KES/@@download/ENCFF612KES.tsv
https://www.encodeproject.org/files/ENCFF024ODR/@@download/ENCFF024ODR.tsv
https://www.encodeproject.org/files/ENCFF908FAV/@@download/ENCFF908FAV.tsv
https://www.encodeproject.org/files/ENCFF761GIK/@@download/ENCFF761GIK.tsv
https://www.encodeproject.org/files/ENCFF282GMF/@@download/ENCFF282GMF.tsv
https://www.encodeproject.org/files/ENCFF999HRP/@@download/ENCFF999HRP.bed.gz
https://www.encodeproject.org/files/ENCFF891RFM/@@download/ENCFF891RFM.tsv
https://www.encodeproject.org/files/ENCFF620EXI/@@download/ENCFF620EXI.tsv
https://www.encodeproject.org/files/ENCFF108CRY/@@download/ENCFF108CRY.tsv
https://www.encodeproject.org/files/ENCFF667LUD/@@download/ENCFF667LUD.tsv
https://www.encodeproject.org/files/ENCFF403RUI/@@download/ENCFF403RUI.tsv
https://www.encodeproject.org/files/ENCFF633HPI/@@download/ENCFF633HPI.tsv
https://www.encodeproject.org/files/ENCFF268DAL/@@download/ENCFF268DAL.tsv
https://www.encodeproject.org/files/ENCFF936GUV/@@download/ENCFF936GUV.tsv
https://www.encodeproject.org/files/ENCFF748GRE/@@download/ENCFF748GRE.bed.gz
https://www.encodeproject.org/files/ENCFF025PCM/@@download/ENCFF025PCM.bed.gz
https://www.encodeproject.org/files/ENCFF733IIC/@@download/ENCFF733IIC.tsv
https://www.encodeproject.org/files/ENCFF638JTR/@@download/ENCFF638JTR.tsv
https://www.encodeproject.org/files/ENCFF632KXS/@@download/ENCFF632KXS.tsv
https://www.encodeproject.org/files/ENCFF126ADB/@@download/ENCFF126ADB.tsv
https://www.encodeproject.org/files/ENCFF353YNE/@@download/ENCFF353YNE.tsv
https://www.encodeproject.org/files/ENCFF325YQY/@@download/ENCFF325YQY.tsv
https://www.encodeproject.org/files/ENCFF711ESU/@@download/ENCFF711ESU.tsv
https://www.encodeproject.org/files/ENCFF363RNZ/@@download/ENCFF363RNZ.tsv
https://www.encodeproject.org/files/ENCFF378CHX/@@download/ENCFF378CHX.tsv
https://www.encodeproject.org/files/ENCFF324JGS/@@download/ENCFF324JGS.tsv
https://www.encodeproject.org/files/ENCFF668MVP/@@download/ENCFF668MVP.tsv
https://www.encodeproject.org/files/ENCFF709CRG/@@download/ENCFF709CRG.tsv
https://www.encodeproject.org/files/ENCFF631DIZ/@@download/ENCFF631DIZ.tsv
https://www.encodeproject.org/files/ENCFF178EPQ/@@download/ENCFF178EPQ.tsv
https://www.encodeproject.org/files/ENCFF095IHG/@@download/ENCFF095IHG.tsv
https://www.encodeproject.org/files/ENCFF863VKF/@@download/ENCFF863VKF.tsv
https://www.encodeproject.org/files/ENCFF172VGZ/@@download/ENCFF172VGZ.tsv
https://www.encodeproject.org/files/ENCFF673AHD/@@download/ENCFF673AHD.tsv
https://www.encodeproject.org/files/ENCFF841KQM/@@download/ENCFF841KQM.tsv
https://www.encodeproject.org/files/ENCFF429BTX/@@download/ENCFF429BTX.tsv
https://www.encodeproject.org/files/ENCFF044AFX/@@download/ENCFF044AFX.tsv
https://www.encodeproject.org/files/ENCFF365IVW/@@download/ENCFF365IVW.tsv
https://www.encodeproject.org/files/ENCFF241KWN/@@download/ENCFF241KWN.tsv
https://www.encodeproject.org/files/ENCFF663TKD/@@download/ENCFF663TKD.tsv
https://www.encodeproject.org/files/ENCFF449FBS/@@download/ENCFF449FBS.tsv
https://www.encodeproject.org/files/ENCFF122TZZ/@@download/ENCFF122TZZ.tsv
https://www.encodeproject.org/files/ENCFF272TNA/@@download/ENCFF272TNA.tsv
https://www.encodeproject.org/files/ENCFF539YEC/@@download/ENCFF539YEC.tsv
https://www.encodeproject.org/files/ENCFF411PVM/@@download/ENCFF411PVM.tsv
https://www.encodeproject.org/files/ENCFF404ZYD/@@download/ENCFF404ZYD.tsv
https://www.encodeproject.org/files/ENCFF370SOC/@@download/ENCFF370SOC.tsv
https://www.encodeproject.org/files/ENCFF449XDM/@@download/ENCFF449XDM.tsv
https://www.encodeproject.org/files/ENCFF449PEQ/@@download/ENCFF449PEQ.tsv
https://www.encodeproject.org/files/ENCFF338FGB/@@download/ENCFF338FGB.tsv
https://www.encodeproject.org/files/ENCFF889PPG/@@download/ENCFF889PPG.tsv
https://www.encodeproject.org/files/ENCFF524JIG/@@download/ENCFF524JIG.tsv
https://www.encodeproject.org/files/ENCFF239XFN/@@download/ENCFF239XFN.tsv
https://www.encodeproject.org/files/ENCFF549QKX/@@download/ENCFF549QKX.tsv
https://www.encodeproject.org/files/ENCFF661CYO/@@download/ENCFF661CYO.tsv
https://www.encodeproject.org/files/ENCFF536CUG/@@download/ENCFF536CUG.tsv
https://www.encodeproject.org/files/ENCFF168GEY/@@download/ENCFF168GEY.tsv
https://www.encodeproject.org/files/ENCFF132AEB/@@download/ENCFF132AEB.tsv
https://www.encodeproject.org/files/ENCFF522SCZ/@@download/ENCFF522SCZ.tsv
https://www.encodeproject.org/files/ENCFF044NVM/@@download/ENCFF044NVM.tsv
EOD

echo "All URLs added to urls.txt"
chmod +x download_encode_rbns_files.sh
